# Generated by Django 4.1.4 on 2022-12-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.CreateModel(
            name='TestQuesuion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.test')),
            ],
        ),
    ]
