# Generated by Django 4.1.4 on 2023-02-25 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.AddField(
            model_name='test',
            name='statistics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.statistic'),
            preserve_default=False,
        ),
    ]
