# Generated by Django 4.1.4 on 2022-12-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_test_question_testquesuion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquesuion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.question'),
        ),
        migrations.AlterField(
            model_name='testquesuion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test'),
        ),
    ]
