# Generated by Django 4.1.4 on 2023-02-25 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statistic_delete_testresult_test_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.AddField(
            model_name='test',
            name='users',
            field=models.ManyToManyField(related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TestStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statistic')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
    ]
