# Generated by Django 4.1.4 on 2023-02-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_test_statistics_remove_test_user_test_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.test'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestStatistic',
        ),
    ]
