# Generated by Django 4.1.4 on 2023-02-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_test_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='users',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test', verbose_name='Theme'),
        ),
    ]
