# Generated by Django 4.1.4 on 2023-02-26 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_test_users_alter_statistic_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test'),
        ),
    ]
