# Generated by Django 4.1.4 on 2023-02-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_statistic_test_alter_statistic_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
    ]
