# Generated by Django 4.1.4 on 2023-02-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.test', verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='statistic'),
        ),
    ]
