# Generated by Django 4.1.4 on 2023-02-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_statistic_test_alter_statistic_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistic',
            new_name='TestStatistic',
        ),
    ]
