# Generated by Django 4.1.4 on 2023-01-02 09:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_test_user_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
